import Foundation
import SwiftUI
import CoreLocation

// MARK: - SituationReport

struct SituationReport: Codable {
    let incidentID: String
    let incidentDate: Date
    let incidentLocation: CLLocationCoordinate2D
    let incidentDescription: String
    let affectedArea: String
    let resourcesAllocated: [String]
    let distributionList: [String]
    
    // NIMS format specific fields
    let incidentType: String
    let incidentStatus: String
    let incidentPriority: String
    let incidentCommander: String
    let incidentTeam: [String]
    
    // Additional metadata
    let reportGeneratedBy: String
    let reportGeneratedDate: Date
}

// MARK: - SituationReportGenerator

class SituationReportGenerator: ObservableObject {
    @Published var report: SituationReport?
    
    func generateReport(incidentData: IncidentData) {
        let report = SituationReport(
            incidentID: UUID().uuidString,
            incidentDate: incidentData.date,
            incidentLocation: incidentData.location,
            incidentDescription: incidentData.description,
            affectedArea: incidentData.affectedArea,
            resourcesAllocated: incidentData.resourcesAllocated,
            distributionList: incidentData.distributionList,
            incidentType: incidentData.type,
            incidentStatus: incidentData.status,
            incidentPriority: incidentData.priority,
            incidentCommander: incidentData.commander,
            incidentTeam: incidentData.team,
            reportGeneratedBy: "ZeroDark AI",
            reportGeneratedDate: Date()
        )
        self.report = report
    }
}

// MARK: - IncidentData

struct IncidentData {
    let date: Date
    let location: CLLocationCoordinate2D
    let description: String
    let affectedArea: String
    let resourcesAllocated: [String]
    let distributionList: [String]
    let type: String
    let status: String
    let priority: String
    let commander: String
    let team: [String]
}

// MARK: - SituationReportView

struct SituationReportView: View {
    @StateObject private var viewModel = SituationReportGenerator()
    let incidentData: IncidentData
    
    var body: some View {
        VStack {
            if let report = viewModel.report {
                ReportDetailView(report: report)
            } else {
                Button("Generate Report") {
                    viewModel.generateReport(incidentData: incidentData)
                }
            }
        }
        .padding()
    }
}

// MARK: - ReportDetailView

struct ReportDetailView: View {
    let report: SituationReport
    
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 10) {
                Text("Incident ID: \(report.incidentID)")
                Text("Incident Date: \(report.incidentDate, formatter: DateFormatter())")
                Text("Incident Location: \(report.incidentLocation.latitude), \(report.incidentLocation.longitude)")
                Text("Incident Description: \(report.incidentDescription)")
                Text("Affected Area: \(report.affectedArea)")
                Text("Resources Allocated: \(report.resourcesAllocated.joined(separator: ", "))")
                Text("Distribution List: \(report.distributionList.joined(separator: ", "))")
                
                // NIMS format specific fields
                Text("Incident Type: \(report.incidentType)")
                Text("Incident Status: \(report.incidentStatus)")
                Text("Incident Priority: \(report.incidentPriority)")
                Text("Incident Commander: \(report.incidentCommander)")
                Text("Incident Team: \(report.incidentTeam.joined(separator: ", "))")
                
                // Additional metadata
                Text("Report Generated By: \(report.reportGeneratedBy)")
                Text("Report Generated Date: \(report.reportGeneratedDate, formatter: DateFormatter())")
            }
            .padding()
        }
    }
}

// MARK: - DateFormatter

extension DateFormatter {
    init() {
        self.dateFormat = "yyyy-MM-dd HH:mm:ss"
    }
}